import type { LocaleCopy } from './types';

export const id: LocaleCopy = {
  code:'id', name:'Bahasa Indonesia', direction:'ltr',
  title:'Arah Kiblat – Kompas Kiblat Online | GetQibla', description:'Temukan arah kiblat dari lokasi Anda dengan kompas langsung di browser ponsel. Gratis, privat, tanpa aplikasi atau akun.',
  heading:'Temukan Kiblat', languageLabel:'Bahasa', compassLabel:'Kompas kiblat', locationAccess:'Kami memerlukan akses lokasi untuk menemukan arah kiblat.', calculation:'Kami menghitung arah terpendek dari lokasi Anda ke Ka’bah di Makkah. Kompas ponsel mengubah arah itu menjadi panah. Lokasi tetap di perangkat ini.',
  start:'Temukan Kiblat', starting:'Mencari Kiblat…', requestingLocation:'Izinkan lokasi untuk menemukan arah Anda.', requestingCompass:'Izinkan kompas untuk mengarahkan panah.', movePhone:'Gerakkan ponsel sampai panah berubah hijau.', aligned:'Anda menghadap Kiblat.', directionLabel:'Arah', angleLabel:'Sudut dari utara', explainAngle:'Penjelasan sudut dari utara', bearingHelp:'Derajat dimulai dari utara searah jarum jam: 0° utara, 90° timur, 180° selatan, 270° barat.', angleSummary:'Sudut dari utara adalah {degrees}°. Kiblat mengarah ke {direction}.', cardinals:['Utara','Timur laut','Timur','Tenggara','Selatan','Barat daya','Barat','Barat laut'],
  recalibrate:'Kalibrasi kompas', calibrationHint:'Gerakkan ponsel perlahan membentuk angka delapan, lalu coba lagi.', calibrationStatus:'Gerakkan ponsel perlahan membentuk angka delapan.', compassUnavailable:'Kompas ponsel tidak tersedia di sini.', compassNoReading:'Ponsel tidak memberikan pembacaan kompas.', compassFallbackText:'Gunakan sudut di atas dengan kompas terpisah. Browser ini tidak memberikan data kompas.', compassFallbackStatus:'Kompas tidak tersedia. Gunakan sudut di atas.', locationUnavailable:'Kami tidak dapat memperoleh lokasi Anda.', browserLocationUnavailable:'Browser ini tidak dapat memberikan lokasi Anda.', browserLocationHelp:'Coba browser yang mengizinkan akses lokasi.', secureConnection:'Lokasi memerlukan koneksi aman.', secureConnectionHelp:'Buka situs melalui HTTPS lalu coba lagi.', locationDenied:'Akses lokasi diperlukan untuk menghitung Kiblat.', locationDeniedHelp:'Izinkan lokasi untuk situs ini lalu coba lagi.', locationNotFound:'Browser tidak dapat menemukan lokasi Anda.', locationNotFoundHelp:'Aktifkan Layanan Lokasi lalu coba lagi.', locationTimeout:'Pencarian lokasi terlalu lama.', locationTimeoutHelp:'Pindah ke tempat dengan sinyal lebih jelas lalu coba lagi.', genericHelp:'Periksa izin browser lalu coba lagi.', locationStatusUnavailable:'Lokasi tidak tersedia.', retry:'Coba lagi', privacy:'Lokasi tetap di perangkat Anda.', footer:'Sedekah jariyah untuk Hadi Khan',
  guide:{title:'Panduan arah kiblat',introduction:'Kiblat adalah arah menuju Ka\'bah di Makkah, Arab Saudi. Umat Islam menghadap ke arah itu saat salat. Arah berubah sesuai lokasi Anda.',stepsTitle:'Cara menghadap Kiblat',steps:[{title:'Izinkan lokasi',text:'Ketuk Temukan Kiblat dan izinkan akses lokasi agar GetQibla dapat menghitung arah dari tempat Anda.'},{title:'Izinkan kompas',text:'Jika ponsel meminta akses gerakan atau kompas, izinkan agar panah merespons saat ponsel diputar.'},{title:'Gerakkan ponsel perlahan',text:'Pegang ponsel dengan stabil dan gerakkan perlahan sampai panah hijau. Jauhkan dari magnet dan benda logam besar.'},{title:'Ikuti panah',text:'Saat panah hijau, arahkan bagian atas ponsel ke arah itu. Itulah Kiblat dari lokasi Anda.'}],calculationTitle:'Cara menghitung arah kiblat',calculation:'GetQibla memakai lintang dan bujur Anda serta koordinat tetap Ka\'bah untuk menghitung arah awal lingkaran besar. Sudut itu dibandingkan dengan arah kompas ponsel. Perhitungan dilakukan di browser.',factsTitle:'Fakta arah kiblat',facts:['Ka\'bah berada di Masjidil Haram, Makkah.','Tidak ada satu arah kompas Kiblat untuk semua orang; arahnya bergantung pada lokasi.','Sudut diukur searah jarum jam dari utara sejati.','Magnet dan logam di sekitar dapat memengaruhi kompas ponsel.'],faqTitle:'Pertanyaan tentang Kiblat',faqs:[{question:'Apa itu arah kiblat?',answer:'Kiblat adalah arah yang dihadapi umat Islam saat salat, menuju Ka\'bah di Masjidil Haram, Makkah.'},{question:'Bagaimana mencari Kiblat di ponsel?',answer:'Ketuk Temukan Kiblat, izinkan lokasi dan kompas, lalu gerakkan ponsel sampai panah hijau.'},{question:'Mengapa arah Kiblat berubah?',answer:'Ka\'bah berada di satu tempat tetap, sedangkan lokasi orang berbeda di seluruh dunia.'},{question:'Apa arti sudut Kiblat?',answer:'Sudut Kiblat diukur searah jarum jam dari utara sejati.'},{question:'Apakah GetQibla menyimpan lokasi?',answer:'Tidak. Perhitungan dilakukan di browser dan lokasi maupun bacaan kompas tidak dikirim ke server.'},{question:'Mengapa kompas ponsel kurang akurat?',answer:'Magnet, logam, kalibrasi dan batas browser dapat memengaruhi pembacaan.'}]}
};
